# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

python:
   version: 3.8
   install:
      - method: pip
        path: .
        extra_requirements:
           - doc