name: Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    uses: biolab/orange-ci-cd/.github/workflows/release.yml@master
    with:
      pure-python: true
    secrets: inherit
